const authorities = {
    mValue: 'mValue',
    getAccount: 'getAccount',
    seed: 'seed',
    createDeveloper: 'createDeveloper',
    updateDeveloper: 'updateDeveloper',
    getDevelopers: 'getDevelopers',
    getDeveloper: 'getDeveloper',
    createAgency: 'createAgency',
    updateAgency: 'updateAgency',
    getAgencies: 'getAgencies',
    getAgency: 'getAgency',
    createPartner: 'createPartner',
    updatePartner: 'updatePartner',
    deletePartner: 'deletePartner',
    getPartners: 'getPartners',
    getPartner: 'getPartner',
    activeAgency: 'activeAgency',
    deactiveAgency: 'deactiveAgency',
    updateAgencyContact: 'updateAgencyContact',
    updateAgencyAboutUs: 'updateAgencyAboutUs',
    getProperties: 'getRentProperties',
    getAccountPlan: 'getAccountPlan',
    createAccountPlan: 'createAccountPlan',
    updateAccountPlan: 'updateAccountPlan',
    updateBillingInformation: 'updateBillingInformation',
    getBillingInformationHistories: 'getBillingInformationHistories',
    getBillingInfo: 'getBillingInfo',
    createBillingInfo: 'createBillingInfo',
    getRoles: 'getRoles',
    grantPermission: 'grantPermission',
    revokePermission: 'revokePermission',
    createSellLeadComment: 'createSellLeadComment',
    createAgent: 'createAgent',
    getAgents: 'getAgents',
    getSellLeadComment: 'getSellLeadComment',
    createStaff: 'createStaff',
    getStaffs: 'getStaffs',
    getStaff: 'getStaff',
    updateMarkAsSellLead: 'updateMarkAsSellLead',
    getDetailSellLead: 'getDetailSellLead',
    getSellLead: 'getSellLead',
    getSalesforces: 'getSalesforces',
    getSalesforce: 'getSalesforce',
    createSalesforce: 'createSalesforce',
    updateSalesforce: 'updateSalesforce',
    deleteSalesforce: 'deleteSalesforce',
    getCrawlerProperty: 'getCrawlerProperty',
    getCrawlerProperties: 'getCrawlerProperties',
    uploadPhotoForPartner: 'uploadPhotoForPartner',
    retrieveImageUrl: 'retrieveImageUrl',
    propertyPush3: 'PROPERTY_PUSH_3',
    propertyPush5: 'PROPERTY_PUSH_5',
    propertyPush10: 'PROPERTY_PUSH_10',
    featuredListings: 'FEATURED_LISTINGS',
    expireListing: 'EXPIRE_LISTING',
    priorityExposure: 'PRIORITY_EXPOSURE',
    createProperty: 'CREATE_PROPERTY',
    updateProperty: 'UPDATE_PROPERTY',
    getListProperties: 'LIST_PROPERTIES',
    createAds: 'CREATE_ADS',
    updateAds: 'UPDATE_ADS',
    createServiceListing: 'CREATE_SERVICE_LISTING',
    updateServiceListing: 'UPDATE_SERVICE_LISTING',
    getDetailServiceListing: 'GET_DETAIL_SERVICE_LISTING',
    getServiceListings: 'GET_SERVICE_LISTINGS',
    getAds: 'GET_ADS',
    removeAds: 'REMOVE_ADS',
    updateFeatureFlags: 'UPDATE_FEATURE_FLAG',
    createComment: 'CREATE_COMMENT',
    getComments: 'GET_COMMENTS',
    getInternationalProjectLeads: 'GET_INTERNATIONAL_PROJECT_LEADS',
    getInternationalProjectLead: 'GET_INTERNATIONAL_PROJECT_LEAD',
    updateInternationalProjectLead: 'UPDATE_INTERNATIONAL_PROJECT_LEAD',
    getSellLeadStatistic: 'GET_SELL_LEAD_STATISTIC',
    createShopspaceAdmin: 'CREATE_SHOPSPACE_ADMIN',
    updateShopspaceAdmin: 'UPDATE_SHOPSPACE_ADMIN',
    getShopspaces: 'GET_SHOPSPACES',
    getShopspace: 'GET_SHOPSPACE',
    createShopspaceAgent: 'CREATE_SHOPSPACE_AGENT',
    updateShopspaceAgent: 'UPDATE_SHOPSPACE_AGENT',
    shopspaceStatistic: 'SHOPSPACE_STATISTIC', // this is for admin
    shopspaceStatisticAdmin: 'SHOPSPACE_STATISTIC_ADMIN', // this is for admin
    shopspaceStatisticAgent: 'SHOPSPACE_STATISTIC_AGENT',
    shopspaceStatisticPartner: 'SHOPSPACE_STATISTIC_PARTNER',
    createShopspacePartner: 'CREATE_SHOPSPACE_PARTNER',
    updateShopspacePartner: 'UPDATE_SHOPSPACE_PARTNER',
    migrateListerSalesforce: 'MIGRATE_LISTER_SALESFORCE',
    migrate: 'MIGRATE'
  }
  
  const roles = {
    administrator: 'ADMINISTRATOR',
    admin: 'ADMIN',
    developer: 'DEVELOPER',
    client: 'CLIENT',
    agent: 'AGENT',
    agency: 'AGENCY',
    agentAgency: 'AGENT_AGENCY',
    agencyAdmin: 'AGENCY_ADMIN',
    user: 'USER',
    partner: 'PARTNER',
    organizationAdmin: 'ORGANIZATION_ADMIN',
    organizationUser: 'ORGANIZATION_USER',
    staff: 'STAFF'
  }
  
  module.exports = {
    roles,
    authorities
  }
  